### numpy 자료구조

numpy 개념 및 배열 설명 -> PPT 참고

In [1]:
import numpy as np

# 배열 생성하는 방법
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [2]:
# 정수와 실수를 혼합했을 때 강제 변환
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [ ]:
# np.array 함수에 직접 원소 넣기
a3 = np.array([0.5, 2, 0.01, 6])
a3

In [3]:
a4 = np.arange(0, 10, 2) # start, stop, step 순서
a4

array([0, 2, 4, 6, 8])

In [4]:
# 배열 객체의 데이터 타입 확인
a1.dtype

dtype('int32')

In [ ]:
a2.dtype

In [5]:
# 다차원 배열 생성
# array()에 직접 인자를 넣어서 다차원 배열 생성
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b1 = np.arange(12).reshape(4,3)
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

배열 생성 실습

리스트 데이터로 원소가 [1,2,3] & [4,5,6]인 2x3 배열 만들기

In [8]:
# 여기에서 배열을 만들어 보세요.
test = np.array([[1,2,3],[4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

배열 연산

In [9]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [10]:
# 기본 연산
arr1+arr2

array([11, 22, 33, 44])

In [11]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [ ]:
arr2**2

In [12]:
arr1 > 20

array([False, False,  True,  True])

In [13]:
# 통계 연산
arr3 = np.arange(1,6)
arr3

array([1, 2, 3, 4, 5])

In [14]:
arr3.sum()

15

In [15]:
arr3.mean()

3.0

In [16]:
arr3.max()

5

In [17]:
# 배열의 인덱싱과 슬라이싱
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [18]:
a1[4]

40

In [19]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [20]:
# 여러 개의 값을 한 번에
a1[[1,3,4]]

array([10, 30, 40])

In [21]:
a1[[1,3,4]] = 1,2,3
a1

array([ 0,  1, 20,  2,  3, 70])

In [22]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [23]:
b1[2:]

array([20, 30, 40, 50])

In [24]:
b1[:3]

array([ 0, 10, 20])

In [26]:
b1[:-1]

array([ 0, 10, 20, 30, 40])

In [27]:
b1[3:6] = 60
b1

array([ 0, 10, 20, 60, 60, 60])